# Generated by Django 2.1.2 on 2018-10-20 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('bid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('btype', models.CharField(max_length=20)),
                ('cDate', models.DateTimeField(auto_now_add=True)),
                ('context', models.TextField()),
                ('isDelete', models.BooleanField(verbose_name=False)),
            ],
        ),
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=20)),
                ('bid', models.CharField(max_length=20)),
                ('isDelete', models.BooleanField(verbose_name=False)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('isDelte', models.BooleanField(verbose_name=False)),
                ('fBlog', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.Blog')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('account', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('petname', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=15, null=True, unique=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('isDelete', models.BooleanField(verbose_name=False)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='fUser',
            field=models.ManyToManyField(to='blog.User'),
        ),
        migrations.AlterUniqueTogether(
            name='collect',
            unique_together={('uid', 'bid')},
        ),
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.User'),
        ),
    ]
