# Generated by Django 2.1.2 on 2018-10-22 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='fBlog',
        ),
    ]
